from __future__ import annotations

import json
import os
import time
from datetime import UTC, datetime
from pathlib import Path
from typing import Any

import numpy as np
import pandas as pd
from Intp20Stage17AdaptiveScalpStrategy import Intp20Stage17TurboAdaptiveScalpStrategy
from pandas import DataFrame


class Intp20Stage18NoKeyHotspotStrategy(Intp20Stage17TurboAdaptiveScalpStrategy):
    """
    Stage-18 hotspot overlay.

    The core entries remain Stage-17.  This layer adds a no-key hotspot score
    from local 1m market behavior and, in dry/live runs, from a JSON cache
    generated by `fetch_stage18_hotspot_cache.py`.
    """

    hotspot_cache_ttl_seconds = 20 * 60
    hotspot_file_reload_seconds = 60
    min_hot_score = 0.10
    high_risk_score = 0.93
    strong_hot_score = 0.76
    max_stake_multiplier = 2.65
    max_boost_leverage = 7.8

    _stage18_cache_data: dict[str, Any] | None = None
    _stage18_cache_loaded_at = 0.0

    @staticmethod
    def _bounded(value: float, lower: float = 0.0, upper: float = 1.0) -> float:
        if not np.isfinite(value):
            return (lower + upper) / 2
        return max(lower, min(upper, value))

    @staticmethod
    def _series_score(series, low: float, high: float):
        return ((series - low) / (high - low)).clip(0.0, 1.0)

    @classmethod
    def _cache_path(cls) -> Path:
        env_path = os.environ.get("STAGE18_HOTSPOT_CACHE_PATH")
        if env_path:
            return Path(env_path)
        return Path(__file__).resolve().parents[1] / "hotspot" / "stage18_hotspot_cache.json"

    @classmethod
    def _load_hotspot_cache(cls) -> dict[str, Any]:
        now = time.time()
        if (
            cls._stage18_cache_data is not None
            and now - cls._stage18_cache_loaded_at < cls.hotspot_file_reload_seconds
        ):
            return cls._stage18_cache_data

        cls._stage18_cache_loaded_at = now
        path = cls._cache_path()
        try:
            data = json.loads(path.read_text(encoding="utf-8"))
        except (OSError, json.JSONDecodeError):
            data = {}
        cls._stage18_cache_data = data if isinstance(data, dict) else {}
        return cls._stage18_cache_data

    @classmethod
    def _fresh_cache_payload(cls, pair: str) -> tuple[dict[str, Any], dict[str, Any]]:
        data = cls._load_hotspot_cache()
        if data.get("degraded"):
            return {}, {}
        generated_at = data.get("generated_at")
        if not generated_at:
            return {}, {}
        try:
            cache_time = datetime.fromisoformat(str(generated_at).replace("Z", "+00:00"))
        except ValueError:
            return {}, {}
        age = datetime.now(UTC) - cache_time
        if age.total_seconds() > cls.hotspot_cache_ttl_seconds:
            return {}, {}
        pairs_data = data.get("pairs")
        pairs = pairs_data if isinstance(pairs_data, dict) else {}
        pair_payload = pairs.get(pair, {})
        global_data = data.get("global")
        global_payload = global_data if isinstance(global_data, dict) else {}
        return (
            pair_payload if isinstance(pair_payload, dict) else {},
            global_payload if isinstance(global_payload, dict) else {},
        )

    def populate_indicators(self, dataframe: DataFrame, metadata: dict) -> DataFrame:
        dataframe = super().populate_indicators(dataframe, metadata)

        volume_15 = dataframe["volume"].rolling(15, min_periods=5).sum()
        volume_base = dataframe["volume"].rolling(240, min_periods=30).mean() * 15
        volume_ratio = (volume_15 / volume_base.replace(0, np.nan)).replace(
            [np.inf, -np.inf], np.nan
        )

        roc_15 = dataframe["close"] / dataframe["close"].shift(15) - 1
        roc_60 = dataframe["close"] / dataframe["close"].shift(60) - 1
        range_pct = (dataframe["high"] - dataframe["low"]) / dataframe["close"]
        volatility_ratio = (
            range_pct.rolling(15, min_periods=5).mean()
            / range_pct.rolling(240, min_periods=30).mean().replace(0, np.nan)
        ).replace([np.inf, -np.inf], np.nan)

        volume_score = self._series_score(volume_ratio.fillna(1.0), 0.8, 3.0)
        momentum_score = (roc_60.abs() / 0.045).clip(0.0, 1.0).fillna(0.0)
        volatility_score = self._series_score(volatility_ratio.fillna(1.0), 0.8, 2.4)
        impulse_score = (roc_15.abs() / 0.025).clip(0.0, 1.0).fillna(0.0)

        dataframe["stage18_hot_score"] = (
            0.34 * volume_score
            + 0.28 * momentum_score
            + 0.23 * volatility_score
            + 0.15 * impulse_score
        ).clip(0.0, 1.0)
        dataframe["stage18_risk_score"] = (
            0.45 * (roc_15.abs() / 0.040).clip(0.0, 1.0).fillna(0.0)
            + 0.35 * (roc_60.abs() / 0.080).clip(0.0, 1.0).fillna(0.0)
            + 0.20 * self._series_score(volatility_ratio.fillna(1.0), 1.2, 3.0)
        ).clip(0.0, 1.0)
        dataframe["stage18_direction_bias"] = (roc_60 / 0.045).clip(-1.0, 1.0).fillna(0.0)
        return dataframe

    def populate_entry_trend(self, dataframe: DataFrame, metadata: dict) -> DataFrame:
        dataframe = super().populate_entry_trend(dataframe, metadata)
        legacy_stage17 = dataframe["enter_tag"].fillna("").str.startswith("s17_")
        if legacy_stage17.any():
            dataframe.loc[legacy_stage17, ["enter_long", "enter_short"]] = 0
            dataframe.loc[legacy_stage17, "enter_tag"] = ""
        if "enter_long" not in dataframe:
            dataframe["enter_long"] = 0
        if "enter_short" not in dataframe:
            dataframe["enter_short"] = 0

        hot = dataframe["stage18_hot_score"].fillna(0.5)
        risk = dataframe["stage18_risk_score"].fillna(0.5)
        bias = dataframe["stage18_direction_bias"].fillna(0.0)

        cold_risk = (hot < self.min_hot_score) & (risk > 0.65)
        long_block = cold_risk | ((risk > self.high_risk_score) & (bias < -0.45))
        short_block = cold_risk | ((risk > self.high_risk_score) & (bias > 0.45))

        dataframe.loc[(dataframe["enter_long"] == 1) & long_block, ["enter_long", "enter_tag"]] = (
            0,
            None,
        )
        dataframe.loc[
            (dataframe["enter_short"] == 1) & short_block, ["enter_short", "enter_tag"]
        ] = (0, None)
        return dataframe

    def _live_cache_enabled(self) -> bool:
        runmode = str(getattr(self, "config", {}).get("runmode", "")).lower()
        return "backtest" not in runmode and "hyperopt" not in runmode

    @staticmethod
    def _row_at_time(dataframe: DataFrame, current_time: datetime | None):
        if dataframe.empty:
            return None
        if current_time is None or "date" not in dataframe:
            return dataframe.iloc[-1]
        candle_time = pd.Timestamp(current_time)
        if candle_time.tzinfo is not None:
            candle_time = candle_time.tz_convert(None)
        dates = pd.to_datetime(dataframe["date"], utc=True, errors="coerce").dt.tz_convert(None)
        current_rows = dataframe.loc[dates <= candle_time]
        if current_rows.empty:
            return None
        return current_rows.iloc[-1]

    def _latest_scores(self, pair: str, current_time: datetime | None) -> dict[str, Any]:
        scores: dict[str, Any] = {
            "hot_score": 0.5,
            "risk_score": 0.5,
            "direction_bias": 0.0,
            "risk_off": False,
        }

        if self.dp:
            try:
                dataframe, _ = self.dp.get_analyzed_dataframe(pair=pair, timeframe=self.timeframe)
                row = self._row_at_time(dataframe, current_time)
                if row is not None:
                    scores["hot_score"] = self._bounded(float(row.get("stage18_hot_score", 0.5)))
                    scores["risk_score"] = self._bounded(float(row.get("stage18_risk_score", 0.5)))
                    scores["direction_bias"] = self._bounded(
                        float(row.get("stage18_direction_bias", 0.0)),
                        -1.0,
                        1.0,
                    )
            except (KeyError, ValueError, TypeError, AttributeError):
                pass

        if self._live_cache_enabled():
            pair_payload, global_payload = self._fresh_cache_payload(pair)
            if pair_payload:
                cache_hot = self._bounded(float(pair_payload.get("hot_score", scores["hot_score"])))
                cache_risk = self._bounded(
                    float(pair_payload.get("risk_score", scores["risk_score"]))
                )
                cache_bias = self._bounded(
                    float(pair_payload.get("direction_bias", scores["direction_bias"])),
                    -1.0,
                    1.0,
                )
                scores["hot_score"] = max(scores["hot_score"], cache_hot)
                scores["risk_score"] = max(scores["risk_score"], cache_risk)
                if abs(cache_bias) > abs(scores["direction_bias"]):
                    scores["direction_bias"] = cache_bias
            scores["risk_off"] = bool(global_payload.get("risk_off", False))
        return scores

    def _entry_allowed(self, side: str, scores: dict[str, Any]) -> bool:
        hot = float(scores["hot_score"])
        risk = float(scores["risk_score"])
        bias = float(scores["direction_bias"])
        if scores["risk_off"] and hot < self.strong_hot_score:
            return False
        if hot < self.min_hot_score and risk > 0.65:
            return False
        if side == "long" and risk > self.high_risk_score and bias < -0.45:
            return False
        if side == "short" and risk > self.high_risk_score and bias > 0.45:
            return False
        return True

    def confirm_trade_entry(
        self,
        pair: str,
        order_type: str,
        amount: float,
        rate: float,
        time_in_force: str,
        current_time: datetime,
        entry_tag: str | None,
        side: str,
        **kwargs,
    ) -> bool:
        if not super().confirm_trade_entry(
            pair,
            order_type,
            amount,
            rate,
            time_in_force,
            current_time,
            entry_tag,
            side,
            **kwargs,
        ):
            return False
        return self._entry_allowed(side, self._latest_scores(pair, current_time))

    def custom_stake_amount(  # type: ignore[override]
        self,
        pair: str,
        current_time: datetime,
        current_rate: float,
        proposed_stake: float,
        min_stake: float | None,
        max_stake: float,
        leverage: float,
        entry_tag: str | None,
        side: str,
        **kwargs,
    ) -> float | None:
        stake = super().custom_stake_amount(
            pair,
            current_time,
            current_rate,
            proposed_stake,
            min_stake,
            max_stake,
            leverage,
            entry_tag,
            side,
            **kwargs,
        )
        if stake is None:
            return None

        scores = self._latest_scores(pair, current_time)
        if not self._entry_allowed(side, scores):
            return None

        hot = float(scores["hot_score"])
        risk = float(scores["risk_score"])
        bias = float(scores["direction_bias"])
        side_bias = bias if side == "long" else -bias
        multiplier = 1.0 + (hot - 0.5) * 0.38 + max(side_bias, 0.0) * 0.12
        multiplier -= max(risk - 0.72, 0.0) * 0.45
        if scores["risk_off"]:
            multiplier *= 0.72
        multiplier = self._bounded(multiplier, 0.72, 1.28)
        adjusted = stake * multiplier
        if min_stake:
            adjusted = max(adjusted, min_stake)
        return min(adjusted, max_stake)

    def leverage(
        self,
        pair: str,
        current_time: datetime,
        current_rate: float,
        proposed_leverage: float,
        max_leverage: float,
        entry_tag: str | None,
        side: str,
        **kwargs,
    ) -> float:
        target = super().leverage(
            pair,
            current_time,
            current_rate,
            proposed_leverage,
            max_leverage,
            entry_tag,
            side,
            **kwargs,
        )
        scores = self._latest_scores(pair, current_time)
        if scores["hot_score"] > self.strong_hot_score and scores["risk_score"] < 0.72:
            target += 0.25
        if scores["risk_score"] > self.high_risk_score or scores["risk_off"]:
            target -= 0.35
        return max(1.0, min(target, max_leverage, self.max_boost_leverage))

    def custom_exit(
        self,
        pair: str,
        trade,
        current_time: datetime,
        current_rate: float,
        current_profit: float,
        **kwargs,
    ) -> str | bool | None:
        scores = self._latest_scores(pair, current_time)
        bias = float(scores["direction_bias"])
        adverse_bias = bias < -0.45 if not trade.is_short else bias > 0.45
        if scores["risk_off"] and current_profit <= -0.005:
            return "stage18_global_risk_exit"
        if scores["risk_score"] > 0.86 and adverse_bias and current_profit <= -0.012:
            return "stage18_hotspot_adverse_exit"
        return super().custom_exit(
            pair,
            trade,
            current_time,
            current_rate,
            current_profit,
            **kwargs,
        )
